### ISSUE TITLE
Application Crash 

### ISSUE THREAD

**Issue by cjwaldron18** [SCCapstone/Cupboard#104]
Application crashes when exiting a shopping list. 
I am using the button from My Cupboard to add an item from My Cupboard to a New Shopping List. After viewing my shopping list, I click the back button to exit and the application crashes. 
The application crashes regardless of if an item is toggled or untouched.

The application successfully crashes on:
Emulator - Android 8.0 API 26
Emulator - Android 8.1 API 27
Galaxy Tab S3 Android 7.0

![cupboard - crash report01 1](https://user-images.githubusercontent.com/23388365/39098082-745350e8-4633-11e8-8980-88870d3c32cf.gif)

**Comment by cjwaldron18** [comment]
04-22 14:02:28.445 6375-6375/com.thecupboardapp.cupboard E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.thecupboardapp.cupboard, PID: 6375
    java.lang.RuntimeException: Unable to pause activity {com.thecupboardapp.cupboard/com.thecupboardapp.cupboard.ShoppingListActivity}: java.lang.NullPointerException: Can't pass null for argument 'pathString' in child()
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3912)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3878)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3852)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3826)
        at android.app.ActivityThread.-wrap15(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1609)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Can't pass null for argument 'pathString' in child()
        at com.google.firebase.database.DatabaseReference.child(Unknown Source:7)
        at com.thecupboardapp.cupboard.ShoppingListActivity.onPause(ShoppingListActivity.java:121)
        at android.app.Activity.performPause(Activity.java:7153)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1408)
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3901)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3878) 
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3852) 
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3826) 
        at android.app.ActivityThread.-wrap15(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1609) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by WillWells** [comment]
You are correct, that looks like the beta release. Make sure you download the one called cupboard.apk, under RC1.
